config:
  MD013: false   # line-length
  MD033: false   # inline HTML
ignores:
  - "vendor/**"
  - "vendor/bundle/**"
  - "node_modules/**"
  - "_site/**"
  - ".devcontainer/**"
  - ".github/**"
  - "WARP.md"
