name: pages

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/configure-pages@v5
      - uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install frontend dependencies
        run: pnpm install --frozen-lockfile

      - name: Build frontend assets
        run: pnpm run build

      - uses: actions/jekyll-build-pages@v1
        with:
          source: .
          destination: ./_site
      - uses: actions/upload-pages-artifact@v4
        with:
          path: ./_site

  deploy:
    if: github.event_name == 'push'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
        with:
          preview: false
